### ISSUE TITLE
Generating wrong subnet when running add peer and configuration scripts

### ISSUE THREAD

**Issue by junzhengca** [ugurrdemirel/wireguard-oracle-cloud-install#4]
When creating new configurations, it asks me for the machine's internal IP, which I assume is going to be from here:

<img width="318" alt="image" src="https://user-images.githubusercontent.com/7855724/178318883-9be3b5ab-d8f7-41e5-ae43-4cc8e9f46e43.png">

but it keeps giving me error, a quick inspection shows that `10.0.0.64` is being converted to `10.0.0.64/24` and written to `settings/ipv4`

<img width="336" alt="image" src="https://user-images.githubusercontent.com/7855724/178319137-b0eadd96-4214-4c87-8859-b4449792c97a.png">

subsequently, the helper script will append `0/24` to the IP

<img width="709" alt="image" src="https://user-images.githubusercontent.com/7855724/178319231-d7b75e15-7ae0-4401-b9fe-2cd9e869e59f.png">

it results in something weird like `10.0.0.64/240/24`, which is not a valid CIDR.

Is there a bug within the script? or am I understanding something wrong?

-------------------------------------------------------

- When it asked for port, I entered 51820
- When it asked for IP, I entered 10.0.0.64
- wg then gives me error in various places complaining 10.0.0.64/240/32 cannot be parsed.

**Comment by ugurrdemirel** [comment]
Hello @junzhengca ,
The script asks you to vpn's internal server ip. This is not related with your server ip adress. The script ask which ip adress should assign for clients. For my personal server, I typed 10.66.66.1 and when I create one more peer, internal vpn adress should be 10.66.66.2. This means wg will identify this client with 10.66.66.2. If you enter you server's ip, it will cause IP conflict.

**Comment by junzhengca** [comment]
This indeed works! I'll close the issue.

Thanks for the timely response.
