### ISSUE TITLE
iptables bad argument

### ISSUE THREAD

**Issue by devinberg** [ugurrdemirel/wireguard-oracle-cloud-install#7]
When running through the setup, I’m getting `Bad argument ‘1b52d2d5f0df’` from add-nat-routing.sh. This occurs when attempting to run add-peer.sh.

**Comment by vaughngx4** [comment]
Do you have anything else set up on the instance? I'm thinking it's getting the wrong network interface or messing something up there. Use `ip a` to find your main interface name and try replacing the interface name in both scripts in the `helper` folder.

**Comment by vaughngx4** [comment]
Otherwise check the contents of `/etc/wireguard/settings/` and make sure the files in there contain what they're meant to(partial IPs for the ipv4 and ipv6 files and a number in the peer.next file).

**Comment by devinberg** [comment]
I do have an installation of Matrix on this server, so that is probably the problem. I was able to fix it as you suggested, I changed `IN_FACE=$(ip -o link show | awk '{print $2,$9}' | tr -d ' ' | grep 'UP' | grep -o [a-z0-9]*: | tr -d ':')` to `IN_FACE="ens3"` in both of the helper scripts.

**Comment by devinberg** [comment]
Thanks a lot!
