### ISSUE TITLE
Script exits unexpectedly if old configs detected

### ISSUE THREAD

**Issue by ajn142** [ugurrdemirel/wireguard-oracle-cloud-install#9]
Per my testing, the existence of any config file that contains “wg0.conf” causes the script to exit, including old files that have been renamed e.g. wg0.conf.old or wg0.conf.bak. 

Pretty sure this is any easy fix to adjust the grep check, I’ll try fixing that in my copy and put in a PR with adjustments if so.

**Comment by ugurrdemirel** [comment]
Thanks for contribution mate <3
